# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  bridge:
    build:
      context: .
    container_name: bridge
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PWD}
    command: --config /config/config.json --verbosity trce --latest
    volumes:
      - ./config:/config
      - ./keys:/keys/
    network_mode: host