{{- if .Values.keystore.password.b64 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keystore.password.fromSecret.name }}
data:
  {{ .Values.keystore.password.fromSecret.key }}: {{ .Values.keystore.password.b64 }}
{{- end }}
